### ISSUE TITLE
Causes problem with standard chai have.length(x) expectation ?

### ISSUE THREAD

**Issue by jeroenvanagt** [matthijsgroen/chai-changes#2] opened 2014-12-15 06:35 UTC
When I enable chai-changes as follows:

    chai = require("chai")
    chai.use require("chai-as-promised")
    chai.use require("chai-changes")
    expect = chai.expect

And use the following code in my test:
    expect(Trade.get_trades(new Date(2014, 8, 14, 9, 24, 0))).to.eventually.have.length(10).notify done

This causes the following error:
    TypeError: Property 'length' of object [object Function] is not a function

When I disable chai-changes it works again. 

What is causing this behavior?

**Comment by valscion** [comment] 2015-04-09 10:57
I came upon this, too. I had `chai-jquery` enabled but it didn't help even after I disabled it. I receive an error "TypeError: number is not a function" on this test line:

```
expect(node.querySelectorAll('label')).to.have.length(values.length);
```

I'll dig deeper and try to find the root cause.

**Comment by valscion** [comment] 2015-04-09 11:23
A-ha! The reason is the `to` part, as when I change my expectation line from
```js
expect(node.querySelectorAll('label')).to.have.length(values.length);
```
to
```js
expect(node.querySelectorAll('label')).have.length(values.length);
```

everything works. The `to` method does not seem to work properly when it is not called as a function but passed on just like a normal language chain method (`be`, `an` etc.)

**Comment by valscion** [comment] 2015-04-09 11:58
See PR #4 for a failing test case which demonstrates this unfortunate issue.

**Comment by matthijsgroen** [comment] 2015-04-14 21:51
see https://github.com/chaijs/chai/issues/427

**Comment by matthijsgroen** [comment] 2015-04-17 10:49
This will be fixed in chai, so closing this pull request

**Closed by matthijsgroen** 2015-04-17 10:49 UTC
